### ISSUE TITLE
Is this tool currently working with the latest rev of Jellyfin?

### ISSUE THREAD

**Issue by Nostradamus1973** [aksiksi/gelatin#12]
Good morning,

I came across this project because there are STILL no viable options to backup Jellyfin. 

So, I wanted to know if this script is viable or not.

Thank you and have a nice day.

**Comment by aksiksi** [comment]
Hi! This tool was designed to import state from a different running Emby or Jellyfin instance. Unfortunately, this project has been inactive for a while, and it isn't fully working.

If you run Jellyfin using Docker, backup becomes a bit easier as you only need to periodically backup the container volumes. See: https://jellyfin.org/docs/general/installation/container#docker
